
all:
	gcc write-file.c -o scripts/write
	gcc encrypt.c -o scripts/encrypt-decrypt
	gcc file-hash.c -o scripts/hash
	gcc rsa-keys.c -o scripts/generate-keys
	gcc diff.c -o scripts/diff

clean:
	rm scripts/**
